alias g="git"
alias gst="git status -s"
alias gl="git log --oneline --graph --decorate --all"
alias ga="git add"
alias gaa="git add -A"
alias gc="git commit"
alias gcm="git commit -m"
alias gca="git commit --amend --no-edit"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gb="git branch"
alias gd="git diff"
alias gf="git fetch --all --prune"
alias gpl="git pull"
alias gps="git push"
alias gpf="git push --force-with-lease"

alias hunk-unstaged="hunk diff --exclude-untracked"
alias hunk-staged="hunk diff --staged"
hunk-past() { hunk show HEAD~"$1"; }
alias hunk-parent="hunk diff @{u}...HEAD"
alias hunk-main="git fetch origin main && hunk diff origin/main...HEAD"